name: marlin_auto_build

on:
  # trigger if we change a build
  push:
    paths:
      - 'builds/**'

  # trigger manually from GitHub UI
  workflow_dispatch:

  # optional: scheduled build
  schedule:
    - cron: '12 17 * * *'

jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@v1
